package config

const CONFIG_FORCE_DEVELOPMENT = "WIREGUARD_DEVELOPMENT"

const CONFIG_SERVER_ADDRESS = "WIREGUARD_SERVER_ADDRESS"
const CONFIG_SERVER_ADDRESS_DEFAULT = "grpc.service.gongt.me"

const CONFIG_SERVER_PORT = "WIREGUARD_SERVER_PORT"
const CONFIG_SERVER_PORT_DEFAULT = 59443
